/**
 * routeData.js
 * Data for mapping the train routes
 * Created: 04-16-2025
 * Last Modified: 07-09-2025
 * Authors: Wanquan Zhao, Hannah Zelko, David Legris
 */

// Maps route numbers to their display names
export const routeNumberToNameMap = {
    1: "Toronto - Ottawa",
    2: "Ottawa - Quebec",
    3: "Toronto - Kingston",
    4: "Montreal - Quebec",
    5: "Toronto - Montreal",
    6: "Windsor - Toronto",
    7: "Sarnia - Toronto",
    8: "London - Toronto",
    9: "Toronto - Niagara Falls"
};

// Maps stop names to an array of route numbers passing through them
export const stopToRouteNumbersMap = {
    "Windsor": [6],
    "Chatham": [6],
    "Glencoe": [6],
    "Sarnia": [7],
    "Wyoming": [7],
    "Strathroy": [7],
    "London": [6, 7, 8],
    "Ingersoll": [6, 8],
    "Woodstock": [6, 8],
    "Brantford": [6, 8],
    "Niagara Falls": [9],
    "St. Catharines": [9],
    "Grimsby": [9],
    "Aldershot": [6, 8, 9],
    "Oakville": [6, 8, 9],
    "St. Marys": [7],
    "Stratford": [7],
    "Kitchener": [7],
    "Guelph": [7],
    "Georgetown": [7],
    "Brampton": [7],
    "Malton": [7],
    "Toronto": [1, 3, 5, 6, 7, 8, 9], 
    "Guildwood": [1, 3, 5],
    "Oshawa": [1, 3, 5],
    "Port Hope": [1, 3, 5],
    "Cobourg": [1, 3, 5],
    "Trenton Junction": [1, 3, 5],
    "Belleville": [1, 3, 5],
    "Napanee": [1, 3, 5],
    "Kingston": [1, 3, 5],
    "Gananoque": [1, 5],
    "Brockville": [1, 5],
    "Smiths Falls": [1],
    "Fallowfield": [1],
    "Ottawa": [1, 2],
    "Casselman": [2],
    "Cornwall": [5],
    "Alexandria": [2],
    "Coteau": [2, 5],
    "Dorval": [2, 5],
    "Montreal": [2, 4, 5],
    "Saint-Lambert": [4],
    "Saint-Hyacinthe": [4],
    "Drummondville": [4],
    "Charny": [4],
    "Sainte-Foy": [4],
    "Quebec": [4] // Quebec City
};

// Mapping from stop name to province
export const stopToProvinceMap = {
    "Windsor": "Ontario",
    "Chatham": "Ontario",
    "Glencoe": "Ontario",
    "Sarnia": "Ontario",
    "Wyoming": "Ontario",
    "Strathroy": "Ontario",
    "London": "Ontario",
    "Ingersoll": "Ontario",
    "Woodstock": "Ontario",
    "Brantford": "Ontario",
    "Niagara Falls": "Ontario",
    "St. Catharines": "Ontario",
    "Grimsby": "Ontario",
    "Aldershot": "Ontario",
    "Oakville": "Ontario",
    "St. Marys": "Ontario",
    "Stratford": "Ontario",
    "Kitchener": "Ontario",
    "Guelph": "Ontario",
    "Georgetown": "Ontario",
    "Brampton": "Ontario",
    "Malton": "Ontario",
    "Toronto": "Ontario",
    "Guildwood": "Ontario",
    "Oshawa": "Ontario",
    "Port Hope": "Ontario",
    "Cobourg": "Ontario",
    "Trenton Junction": "Ontario",
    "Belleville": "Ontario",
    "Napanee": "Ontario",
    "Kingston": "Ontario",
    "Gananoque": "Ontario",
    "Brockville": "Ontario",
    "Smiths Falls": "Ontario",
    "Fallowfield": "Ontario",
    "Ottawa": "Ontario",
    "Casselman": "Ontario",
    "Alexandria": "Ontario",
    "Cornwall": "Ontario",
    "Coteau": "Quebec",
    "Dorval": "Quebec",
    "Montreal": "Quebec",
    "Saint-Lambert": "Quebec",
    "Saint-Hyacinthe": "Quebec",
    "Drummondville": "Quebec",
    "Charny": "Quebec",
    "Sainte-Foy": "Quebec",
    "Quebec": "Quebec"
};